# config file version
apiVersion: 1

# list of datasources to insert/update
# available in the database
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: $WEATHER_DB_HOSTNAME:5432
    database: $WEATHER_DB_NAME
    user: $WEATHER_DB_USERNAME
    secureJsonData:
      password: $WEATHER_DB_PASSWORD
    jsonData:
      sslmode: 'require'
      database: $WEATHER_DB_NAME
