CREATE TABLE IF NOT EXISTS weather_world_forecast (
    country                        VARCHAR(100),
    location_name                  VARCHAR(100),
    latitude                      NUMERIC(9,6),
    longitude                     NUMERIC(9,6),
    temperature_celsius           NUMERIC(5,2),
    temperature_fahrenheit        NUMERIC(5,2),
    condition_text                VARCHAR(255),
    wind_mph                     NUMERIC(6,2),
    wind_kph                     NUMERIC(6,2),
    wind_degree                  SMALLINT,
    wind_direction               VARCHAR(20),
    pressure_mb                  NUMERIC(7,2),
    pressure_in                  NUMERIC(7,3),
    precip_mm                   NUMERIC(7,3),
    precip_in                   NUMERIC(7,3),
    humidity                    SMALLINT,
    cloud                       SMALLINT,
    feels_like_celsius          NUMERIC(5,2),
    feels_like_fahrenheit       NUMERIC(5,2),
    visibility_km               NUMERIC(7,3),
    visibility_miles            NUMERIC(7,3),
    uv_index                   SMALLINT,
    gust_mph                   NUMERIC(6,2),
    gust_kph                   NUMERIC(6,2),
    air_quality_carbon_monoxide    NUMERIC(10,4),
    air_quality_ozone              NUMERIC(10,4),
    air_quality_nitrogen_dioxide   NUMERIC(10,4),
    air_quality_sulphur_dioxide    NUMERIC(10,4),
    air_quality_pm2_5               NUMERIC(10,4),
    air_quality_pm10               NUMERIC(10,4),
    air_quality_us_epa_index       SMALLINT,
    air_quality_gb_defra_index     SMALLINT,
    prediction_date             DATE,
    model_uri                   VARCHAR(200),
    _load_timestamp             TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_global_weather_last_updated ON weather_world_forecast(prediction_date);
